language: ruby
rvm:
- 2.4
- 2.5
- 2.6
deploy:
  provider: rubygems
  api_key:
    secure: Oh07PSYCNSlfDT1PRx2nhNSLuM22vdYLQPPhakF7duAYOVinBYJpbwt5Ld7EhC1NlOq1eXhAjVggLe+YqpRJXTqROiyW3SUbcn/u/mYmYxPOkEhi5wAlmK36rwdLrMY/X07RLD8hciMNnur22Btdj0AhxNX7Au3j7LI+eeRnza0=
  on:
    tags:
      true
